name: Backend CD

on:
    workflow_run:
        workflows: ["Backend CI"]
        types:
            - completed

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v4

            - name: Pull Docker image
              run: sudo docker compose pull

            - name: Start Containers
              env:
                  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
                  DB_NAME: ${{ secrets.DB_NAME}}
                  DB_USER: ${{ secrets.DB_USER}}
                  DB_HOST: ${{ secrets.DB_HOST}}
                  DB_PORT: ${{ secrets.DB_PORT}}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
                  PORT: ${{ secrets.PORT}}
                  KEY: ${{ secrets.KEY}}
                  SECTRET: ${{ secrets.SECTRET}}
                  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY}}
              run: sudo docker compose up --force-recreate
