name: Frontend CI

on:
    push:
        branches: ["main", "docker"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Dependencies
              run: yarn install

            - name: Build Vite Artifacts
              working-directory: ./React_Project
              env:
                  VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}
                  VITE_ENVIRONMENT: ${{secrets.VITE_ENVIRONMENT}}
                  VITE_WEBSOCKET_URL: ${{secrets.VITE_WEBSOCKET_URL}}
                  SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
              run: npm run build

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Build
                  path: ./React_Project/dist
                  retention-days: 7
