name: Frontend CD

on:
    workflow_run:
        workflows: ["Frontend CI"]
        types:
            - completed

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Remove existing artifacts
              run: |
                  if [ -d "/home/ec2-user/projects-listing/React_Project/dist" ]; then
                    rm -rf /home/ec2-user/projects-listing/React_Project/dist
                  fi

            - name: Download Build Artifact
              uses: actions/download-artifact@v4
              with:
                  run-id: ${{ github.event.workflow_run.id }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  name: Build
                  path: /home/ec2-user/projects-listing/React_Project/dist
